version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"

  # Python
  - package-ecosystem: "pip"
    directory: "/python"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      python:
        patterns:
          - "*"

  # Rust
  - package-ecosystem: "cargo"
    directory: "/rust"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      rust:
        patterns:
          - "*"

  # Go
  - package-ecosystem: "gomod"
    directory: "/go"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      go:
        patterns:
          - "*"

  # Kotlin
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "*"

  # Java
  - package-ecosystem: "gradle"
    directory: "/java"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      java:
        patterns:
          - "*"

  # Swift
  - package-ecosystem: "swift"
    directory: "/swift"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      swift:
        patterns:
          - "*"

  # C#
  - package-ecosystem: "nuget"
    directory: "/csharp"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      csharp:
        patterns:
          - "*"

  # .NET SDK
  - package-ecosystem: "dotnet-sdk"
    directory: "/csharp"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      dotnet:
        patterns:
          - "*"

  # TypeScript
  - package-ecosystem: "bun"
    directory: "/typescript"
    commit-message:
      prefix: ""
    schedule:
      interval: "daily"
    groups:
      typescript:
        patterns:
          - "*"
