name: Kotlin Native

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/kotlin-native.yml"
      - "kotlin-native/**"
      - "!README.md"
  pull_request:
    paths:
      - ".github/workflows/kotlin-native.yml"
      - "kotlin-native/**"
      - "!README.md"

# Cancel previous runs for PRs but not pushes to main
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: kotlin-native

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          # Fetch all history including 'origin/main' so Spotless can detect the changes
          fetch-depth: 0

      - name: Cache Gradle wrapper and build outputs
        uses: actions/cache@v4
        with:
          path: |
            kotlin-native/.gradle
            kotlin-native/build
          key: gradle-wrapper-kotlin-native-${{ runner.os }}-${{ hashFiles('kotlin-native/gradle/wrapper/gradle-wrapper.properties', 'kotlin-native/build.gradle.kts') }}
          restore-keys: gradle-wrapper-kotlin-native-${{ runner.os }}-

      - name: Build
        run: chmod +x build.sh && ./build.sh

      - name: Lint
        run: ./gradlew spotlessCheck

      - name: Test
        run: ./gradlew nativeTest
